apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-ts

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
  selector:
    matchLabels:
      api: app-ts
  template:
    metadata:
      labels:
        api: app-ts
    spec:
      containers:
        - name: app-ts
          image: amakusashirou/app-ts:v6
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-ts
            - secretRef:
                name: app-ts-secrets
#          env:
#            - name: APP
#              valueFrom:
#                configMapKeyRef:
#                  name: app-ts
#                  key: app-name
#            - name: API_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: app-ts-secrets
#                  key: api-key
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 30
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
